version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - app
